# create your drupal and postgres config here, based off the last assignment

version: '3.1'

services:
  drupal:
    image: drupal:8.2
    ports:
      - 8081:80
    volumes: #we could just pass the volume drupal has inside the container and let docker create an anonymous work like so : /var/www/html/modules
      #but here we want named volumes
      - drupal-modules:/var/www/html/modules \
      - drupal-profiles:/var/www/html/profiles \
      - drupal-sites:/var/www/html/sites \
      - drupal-themes:/var/www/html/themes \
    depends_on:
      - mypostgres

  mypostgres:
    image: postgres:12.1
    volumes:
    - drupal-data:/var/lib/postgresql/data
    secrets:
      POSTGRES_PASSWORD_FILE:
        -my-external-pass


secrets:
    my-external-pass:
        external: true
    

volumes: #in docker compose we need to create the named volumes for them to be available for the services
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
  drupal-data:
